export const material_rows = [
  {
    id: 1,
    material: "Material 1",
    subMaterial: "SubMaterial 1",
    umo: "UOM1",
    Qty: 10,
  },
  {
    id: 2,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 3,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 4,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 5,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 6,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 7,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 8,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 9,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },

  {
    id: 10,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
  {
    id: 11,
    material: "Material 2",
    subMaterial: "SubMaterial 2",
    umo: "UOM2",
    Qty: 20,
  },
];
